RegistrationProject/Models/CustomerModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RegistrationProject.Models
{
    public class CustomerModel
    {
        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "Entry for field exceeds allowable character length")]
        [Required(ErrorMessage = "A first name is required")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(50, ErrorMessage = "Entry for field exceeds allowable character length")]
        [Required(ErrorMessage = "A last name is required")]
        public string LastName { get; set; }

        [Display(Name = "Address Line 1")]
        [StringLength(50, ErrorMessage = "Entry for field exceeds allowable character length")]
        [Required(ErrorMessage = "An address is required")]
        public string AddressLine1 { get; set; }

        [Display(Name = "Address Line 2 (Optional)")]
        [StringLength(50, ErrorMessage = "Entry for field exceeds allowable character length")]
        public string AddressLine2 { get; set; }

        [Display(Name = "City")]
        [StringLength(35, ErrorMessage = "Entry for field exceeds allowable character length")]
        [Required(ErrorMessage = "A city is required")]
        public string City { get; set; }

        [Display(Name = "State")]
        [RegularExpression(@"^((?!NA).)*$", ErrorMessage = "A state is required")]
        [Required(ErrorMessage = "A state is required")]
        public string State { get; set; }

        [Display(Name = "ZIP Code")]
        [RegularExpression(@"^\d{5}(-\d{4})?$", ErrorMessage = "ZIP code is invalid")]
        [Required(ErrorMessage = "A zip code is required")]
        public string Zipcode { get; set; }

        [Display(Name = "Country")]
        [StringLength(30, ErrorMessage = "Entry for field exceeds allowable character length")]
        [Required(ErrorMessage = "A country is required")]
        public string Country { get; set; }

        [Display(Name = "Registration Date")]
        public DateTime RegistrationDate { get; set; }
    }
}

RegistrationProject/Controllers/RegistrationController.cs
using DataLibrary.Orchestrators;
using RegistrationProject.Models;
using System.Web.Mvc;

namespace RegistrationProject.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly IRegistrationOrchestrator registrationOrchestrator;

        public RegistrationController(IRegistrationOrchestrator registrationOrchestrator)
        {
            this.registrationOrchestrator = registrationOrchestrator;
        }

        [HttpGet]
        public ViewResult Index()
        {
            return View("Registration");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ViewResult Register(CustomerModel model)
        {
            if (ModelState.IsValid)
            {
                bool customerAddedSuccessfully = registrationOrchestrator.AddCustomer(model.FirstName, 
                    model.LastName, 
                    model.AddressLine1, 
                    model.AddressLine2, 
                    model.City, 
                    model.State, 
                    model.Zipcode, 
                    model.Country);

                if (customerAddedSuccessfully)
                {
                    return View("Confirmation", model);
                }
                else
                {
                    return View("RegistrationFailed");
                }
            }

            return View();
        }
    }
}

RegistrationProject/Controllers/ReportingController.cs
using DataLibrary.Orchestrators;
using RegistrationProject.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace RegistrationProject.Controllers
{
    public class ReportingController : Controller
    {
        private readonly IReportingOrchestrator reportingOrchestrator;

        public ReportingController(IReportingOrchestrator reportingOrchestrator)
        {
            this.reportingOrchestrator = reportingOrchestrator;
        }
        public ViewResult Index()
        {
            List<CustomerModel> customers = new List<CustomerModel>();

            foreach (var customer in reportingOrchestrator.GetCustomers())
            {
                customers.Add(new CustomerModel
                {
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    AddressLine1 = customer.AddressLine1,
                    AddressLine2 = customer.AddressLine2,
                    City = customer.City,
                    State = customer.State,
                    Zipcode = customer.Zipcode,
                    Country = customer.Country,
                    RegistrationDate = customer.RegistrationDate
                });
            }

            return View("AdminReport", customers);
        }
    }
}

RegistrationProject/Views/Reporting/AdminReport.cshtml
@model IEnumerable<RegistrationProject.Models.CustomerModel>

@{
    ViewBag.Title = "Registered User Report";
}

<h2>Registered User Report</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zipcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AddressLine1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AddressLine2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zipcode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationDate)
        </td>
    </tr>
}

</table>

RegistrationProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Register", "Index", "Registration")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Reporting")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Software Engineering Assessment</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>